### PR TITLE
Create civiproxy.yml

### PR DESCRIPTION
**Pull request by ErikHommel**
Would like to add the CiviProxy Guide to civicrm-docs as a separate book.

Remark: I had some trouble understanding this part of the documentation guide:

> When you're ready, you make a pull request on our publishing system to add the necessary configuration for your guide, so that it gets published to docs.civicrm.org.

It was not immediately clear to me that I had to fork the repo and add my own yml file. Would probably be nice to include that part in the documentation guide to?

### CODE REVIEW

**Comment by seanmadsen** [comment]
@ErikHommel I've merged this now, but the new guide won't be immediately available. I'll let you know when, and I'll explain more at that point.

**Comment by seanmadsen** [comment]
@ErikHommel your new guide is now [published here](https://docs.civicrm.org/civiproxy/en/latest/). Looks very cool! :star2: 

If you have not yet [set up automatic publishing](https://docs.civicrm.org/dev/en/latest/documentation/extensions/#automatic-publishing) you'll need to do that in order for *future* changes to your guide to get published. If you *don't* set up automatic publishing, then every time you commit an edit to your repo you'll need to manually re-publish the guide visiting the following URL:

`https://docs.civicrm.org/admin/publish/civiproxy`

Definitely let me know if you have any more questions about the process. I know it's a bit confusing.

**Comment by seanmadsen** [comment]
@ErikHommel I hope [these changes](https://github.com/civicrm/civicrm-dev-docs/commit/47d746aa345e1ec3906b063e276ac7dd069c1cdd) will address your feedback about the process. Note that in addition to adding more instructions about the step where you create a *fork*, I *also* changed the instructions to point to GitLab (instead of GitHub) because I'm trying to move our docs workflow over there. It's pretty similar though. Let me know if you have more thoughts.

**Comment by ErikHommel** [comment]
@seanmadsen thanks Sean! I will setup the automatic publishing. The changes to the process documentation work for me. Purely out of interest, what are the triggers for a move to GitLab?

**Comment by seanmadsen** [comment]
re: GitLab... 

* The change is coming from the core team, not me. Read [Josh's blog post about it](https://civicrm.org/blog/josh/adopting-gitlab-an-introduction). I'm just trying to embrace this change.
* Additionally, I think GitLab is really cool! I've played with it a bit after Mathieu set it up at lab.civicrm.org. I'm no expert but as far as I can tell, it does everything that GitHub does, but... basically *better*. I've found several very nice features in GitLab which are not in GitHub. Also it's cool that it's open source.

**Pull request merged**
